// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Sentiment.Model
{
    public class ModelInput
    {
        [ColumnName("Text"), LoadColumn(0)]
        public string Text { get; set; }


        [ColumnName("Sentiment"), LoadColumn(1)]
        public string Sentiment { get; set; }
    }
}
